### ISSUE TITLE
Bump to support Dart2 stable

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/http_multi_server#9]

**Comment by chalin** [comment]
This was done in #8, https://github.com/dart-lang/http_multi_server/pull/8/files#r192845606: https://github.com/dart-lang/http_multi_server/blob/674319375d555c04cd026ebb56b20a5f365dac5b/pubspec.yaml#L8

I'll submit a PR for a follow-up cleanup (since the analysis options still contains `strong-mode: true`.

**Comment by kevmoo** [comment]
Oops! Thanks

**Comment by chalin** [comment]
See #10
